export const routeNames = {
  dashboard: "/",
  patients: "/patients",
  families: "/families",
  appointments: "/appointments",
  payments: "/accounts/payments",
  banks: "/accounts/banks",
  cash: "/accounts/cash",
  cheques: "/accounts/cheques",
  payrolls: "/accounts/payrolls",
  users: "/users",
  staff: "/hr/staff",
  departments: "/hr/departments",
  settings: "/settings",
  logout: "/logout",
};
